name: agency
channels:
  - pytorch
  - conda-forge
  - nvidia # for brax
dependencies:
  - python=3.9
  - pytorch=1.12.0
  - torchvision=0.13.0
  - cudatoolkit=11.3
  - cuda-nvcc # for brax
  - pip
  - pip:
    - "git+https://github.com/jackharmer/gym-minigrid.git"
    - gym[atari,Box2D,other,accept-rom-license]==0.25.1
    - pytest
    - mlagents_envs==0.28.0
    - tensorboard
    - atari_py
    - envpool
    - einops
    - pgzip
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - jax[cuda]==0.3.25
    - brax==0.0.13
    - wandb
