name: agency
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pip
  - pip:
    # TODO: This gym fork allows rendering, but needs updating to the latest gym version.
    # - "git+https://github.com/jackharmer/gym.git#egg=gym[atari,Box2D,other,accept-rom-license]"
    - "git+https://github.com/jackharmer/gym-minigrid.git"
    - gym[atari,Box2D,other,accept-rom-license]==0.23.1
    - pytest
    - mlagents_envs==0.28.0
    - tensorboard
    - atari_py